### ISSUE TITLE
Cannot find module 'next/dist/compiled/https-proxy-agent'

### ISSUE THREAD

**Issue by JDanP** [adhithiravi/Next.js-Fundamentals#9]
Hi! 
I'm watching your video https://app.pluralsight.com/ilx/video-courses/55381bad-ecee-464e-89df-d71fa1562a9e/bfe195a2-4a66-41ef-92d0-6e536075a98c/f1e5b2e5-6e34-4542-947a-834ba846d3c2
to learn Next. I've downloaded the repo, run `yarn` successfully but when I run `yarn dev` there is sth missing

![image](https://github.com/adhithiravi/Next.js-Fundamentals/assets/43183212/62c8c2de-bdb7-44b8-94c8-cad5507eed87)

**Comment by JDanP** [comment]
node v16.15.1

**Comment by JDanP** [comment]
Solved partially with https://github.com/adhithiravi/Next.js-Fundamentals/pull/6

**Comment by adhithiravi** [comment]
This should be fixed now, with the upgraded packages. Thanks!
